module.exports = {
  mutoSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*
  someSidebar: {
    "Muto": [ "muto"],
    "LiveUI": ["intro"],
    "Getting Started": ["zero-configuration", "getting-started-react", "getting-started-react-native"],
    "Advanced": ["organizing-code-base", "single-codebase-react", "single-codebase-react-native", "multiple-codebases-react", "multiple-codebases-react-native", "info-page", "debugging", "profile-options", "building"],
    "Explore The Code": ["liveui.config"],
    "API References": ["liveui", "liveui-core", "liveui-react", "liveui-react-native"],
    "Sample Projects": ["book-universe-multiple-codebase-react", "book-universe-single-codebase-react", "eventies-multiple-codebase-react-native", "todo-single-codebase-react-native"],
    "Contributing": ["contributing", "code-of-conduct"],
    "Support": ["troubleshooting"],
  },
  docs: [
    {
      type: 'category',
      label: 'LiveUI Guides',
      collapsible: true,
      collapsed: false,
      items: [
        'troubleshooting',
        {
          type: 'category',
          label: 'C Docs',
          items: ["zero-configuration", "getting-started-react", "getting-started-react-native"],
        },
      ],
    },
  ], */
};
 